//HOLA MUNDO
//HOLA MUNDO OTRA VEZ

//INICIO DE LA HISTORIA

//HOLA ISAAC, NECESITAS CONFIAR, PORQUE SI NO CONFIAS NO HAY CONFIANZA
//HOLA MUNDO
//HOLIS
//MI BEBITO FIU FIUUUUUUUUUUUUUUUUU
//CARAMELO DE CHOCOLATE